from art import *
import emoji 
import time
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("Hello World...")
print("")
time.sleep(3.0)
print("How are you ?")
print("")
time.sleep(3.0)
print("Let me tell you brief history of MILVIK BIMA")
print("")
time.sleep(3.0)
print("in Star Trek Style...!!")
print(emoji.emojize(":winking_face_with_tongue:"))
print("")
time.sleep(3.0)
print("Ready ??")
print("")
time.sleep(5.0)
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
tprint("2010",font="block",chr_ignore=True)
tprint("The Story Begins",font="cybermedum")
print("BIMA launches in Ghana. In partnership with Tigo we bring Family Care Insurance to customers.")
print("")
print("")
print("")
print("")
print("")
time.sleep(8.0)
print("")
print("")
print("")
print("")
print("")
tprint("2011",font="block",chr_ignore=True)
tprint("Second Market",font="cybermedum")
print("BIMA launches its second product with Tigo in Ghana and starts operations in its second market: Tanzania.")
print("")
print("")
print("")
print("")
print("")
time.sleep(8.0)
print("")
print("")
print("")
print("")
print("")
tprint("2012",font="block",chr_ignore=True)
tprint("First step into Asia.",font="cybermedum")
print("Kinnevik and Millicom invest in BIMA and we launch 2 new markets: Senegal and Bangladesh.")
print("")
print("")
print("")
print("")
print("")
time.sleep(8.0)
print("")
print("")
print("")
print("")
print("")
tprint("2013",font="block",chr_ignore=True)
tprint("We expand Product offer",font="cybermedum")
print("We launch our very first Hospital insurance product. Leapfrog Investments commits funding to BIMA as we expand to our 6th market!")
print("")
print("")
print("")
print("")
print("")
time.sleep(8.0)
print("")
print("")
print("")
print("")
print("")
tprint("2014",font="block",chr_ignore=True)
tprint("Million mark",font="cybermedum")
print("Not only is it our most prolific year for market launches, with 7 new countries going live, we also hit milestone of one million policies sold.")
print("")
print("")
print("")
print("")
print("")
time.sleep(8.0)
print("")
print("")
print("")
print("")
print("")
tprint("2015",font="block",chr_ignore=True)
tprint("Beyond insurance",font="cybermedum")
print("BIMA launches mHealth services. We now give people access to vital health services at the touch of a button. We go live in Pakistan.")
print("")
print("")
print("")
print("")
print("")
time.sleep(8.0)
print("")
print("")
print("")
print("")
print("")
tprint("2016",font="block",chr_ignore=True)
tprint("All about empowerment",font="cybermedum")
print("We launch RUN, BIMAs womens empowerment programme to promote gender equality across our markets.")
print("")
print("")
print("")
print("")
print("")
time.sleep(8.0)
print("")
print("")
print("")
print("")
print("")
tprint("2017",font="block",chr_ignore=True)
tprint("Hundred million investment",font="cybermedum")
print("Axiata and Allianz X invest $16.8 million and $96.2 million for the continued expansion of BIMA.")
print("")
print("")
print("")
print("")
print("")
time.sleep(8.0)
print("")
print("")
print("")
print("")
print("")
tprint("2018",font="block",chr_ignore=True)
tprint("m-Health Evolution",font="cybermedum")
print("BIMA introduces exciting new features to its mHealth offer, including discounts at laboratories, home medicine delivery and a customer app in two markets Ghana and Bangladesh. We also launch BIMA in Malaysia.")
print("")
print("")
print("")
print("")
print("")
time.sleep(8.0)
print("")
print("")
print("")
print("")
print("")
tprint("2019",font="block",chr_ignore=True)
tprint("Winning Mobile Oscars",font="cybermedum")
print("BIMA wins Best Innovation for Health and Biotech at the GSMA GLOMO awards, considered the Oscars of the mobile industry.")
print("")
print("")
print("")
print("")
print("")
time.sleep(8.0)
print("")
print("")
print("")
print("")
print("")
tprint("2020",font="block",chr_ignore=True)
tprint("Importance during Pandemic",font="cybermedum")
print("Pandemic made people realize the importance of BIMA even more. Insurance and health service should never be luxury but rather a necessary that each and everyone can afford. And we at BIMA promise in delivering that !!")
print("")
print("")
print("")
print("")
print("")
time.sleep(14.0)
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("Like what you see ?")
print("")
print("Download the complete source code for this project from below link - ")
print("https://github.com/Anilkutsa/milvik_art.git")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
time.sleep(5.0)
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("Thanks for sitting through these interesting or rather awkward slideshow !!")
print(emoji.emojize(":grinning_face_with_big_eyes:")) 
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
time.sleep(3.0)
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("You deserve a pat on a back. Enjoy this cool animation that will cheer you up !!")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
time.sleep(3.0)
